#!/bin/bash

tmpout=$(mktemp)
errout=$(mktemp)

if ${@:2} $1 > $tmpout 2> $errout ; then
    misc/check-no-diff $1 $tmpout
    status=$?
else
    cat $tmpout
fi

cat $errout

rm $errout
rm $tmpout

exit $status
