# Copyright 2020 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

# Keep in sync with llvm-hs@llvm-15: https://github.com/llvm-hs/llvm-hs/blob/llvm-15/stack.yaml
resolver: lts-20.16 # GHC 9.2.7

packages:
- .

extra-deps:
  - github: llvm-hs/llvm-hs
    commit: 80e0de0f96eb78288c88fda0eaba0f7cf5d38a30 # llvm-15, 2023-04-03
    subdirs:
      - llvm-hs
      - llvm-hs-pure
  - megaparsec-8.0.0
  - prettyprinter-1.6.2
  - store-0.7.8@sha256:0b604101fd5053b6d7d56a4ef4c2addf97f4e08fe8cd06b87ef86f958afef3ae,8001
  - store-core-0.4.4.4@sha256:a19098ca8419ea4f6f387790e942a7a5d0acf62fe1beff7662f098cfb611334c,1430
  - th-utilities-0.2.4.1@sha256:b37d23c8bdabd678aee5a36dd4373049d4179e9a85f34eb437e9cd3f04f435ca,1869

nix:
  enable: false
  packages: [ libpng llvm_12 pkg-config zlib ]

ghc-options:
  containers: -fno-prof-auto -O2
  hashable: -fno-prof-auto -O2
  llvm-hs-pure: -fno-prof-auto -O2
  llvm-hs: -fno-prof-auto -O2
  megaparsec: -fno-prof-auto -O2
  parser-combinators: -fno-prof-auto -O2
  prettyprinter: -fno-prof-auto -O2
  store-core: -fno-prof-auto -O2
  store: -fno-prof-auto -O2
  unordered-containers: -fno-prof-auto -O2
