#!/bin/bash

tmpout=$(mktemp)
tmpdiff=$(mktemp)

if ${@:2} $1 > $tmpout ; then
    diff --left-column -B -y --color=always $1 $tmpout > $tmpdiff \
       && echo OK || cat $tmpdiff
else
    cat $tmpout
fi

rm $tmpout
rm $tmpdiff
