name = "DexCall"
uuid = "bb22f25d-cb49-471c-b017-930e329a2928"
version = "0.1.0"

[deps]
CombinedParsers = "5ae71ed2-6f8a-4ed1-b94f-e14e8158f19e"

[compat]
CombinedParsers = "^0.2"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
