name: Update HTML docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            install_deps: sudo apt-get install llvm-12-tools llvm-12-dev pkg-config wamerican
            path_extension: /usr/lib/llvm-12/bin

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        ${{ matrix.install_deps }}
        echo "${{ matrix.path_extension }}" >> $GITHUB_PATH

    - name: Get example files
      run: |
        wget http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-images-idx3-ubyte.gz
        wget http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/t10k-labels-idx1-ubyte.gz
        gunzip t10k-images-idx3-ubyte.gz t10k-labels-idx1-ubyte.gz
        mv t10k-images-idx3-ubyte t10k-labels-idx1-ubyte $GITHUB_WORKSPACE/examples/

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          $GITHUB_WORKSPACE/.stack-work
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal', 'stack*.yaml') }}
        restore-keys: ${{ runner.os }}-

    - name: Build
      run: make build

    - name: Generate docs
      run: make docs

    - name: Deploy to GitHub Pages
      uses: "JamesIves/github-pages-deploy-action@3dbacc7e69578703f91f077118b3475862cb09b8" # 4.1.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: pages    # The folder the action should deploy.
          clean: false     # If true, automatically remove deleted files from the deploy branch.
          commit-message: Updating gh-pages from ${{ github.sha }}
