name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEX_CI: 1

concurrency:
  group: python-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            install_deps: |
              curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
              sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main"
              sudo apt-get update
              sudo apt-get -y install clang-15 llvm-15-dev llvm-15-tools
              sudo apt-get -y install pkg-config wget gzip wamerican
            path_extension: /usr/lib/llvm-15/bin

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install system dependencies
      run: |
        pip install pytest jax jaxlib
        ${{ matrix.install_deps }}
        echo "${{ matrix.path_extension }}" >> $GITHUB_PATH

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          ~/.cache/pip
          $GITHUB_WORKSPACE/.stack-work
        key: ${{ runner.os }}-v2-python-${{ hashFiles('**/*.cabal', 'stack*.yaml') }}
        restore-keys: |
          ${{ runner.os }}-v2-python-
          ${{ runner.os }}-v2-

    - name: Build
      run: make build-ffis

    - name: Install Python bindings
      run: pip install -e $GITHUB_WORKSPACE/python

    - name: Run tests
      run: pytest python/tests -v
